###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

services:
  actual-development:
    container_name: test-app
    image: test-app:latest
    environment:
      - HTTPS
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    restart: 'no'
    networks:
      - dast-network

networks:
  dast-network:
    external: true
